export const ADD_DATASET_LIST = "ADD_DATASET_LIST";

export const SET_DATASET_LIST = "SET_DATASET_LIST";

export const CLEAN_DATASET_LIST = "CLEAN_DATASET_LIST";

export const SET_USER_LIST = "SET_USER_LIST";

export const SET_TAGS = "SET_TAGS";

export const SET_METADATAS = "SET_METADATAS";

export const SET_PERSONAL_DATASET_ID = "SET_PERSONAL_DATASET_ID";

export const SET_CONTAINERS_PERMISSION = "SET_CONTAINERS_PERMISSION";

export const SET_USER_ROLE = "SET_USER_ROLE";

export const SET_UPLOAD_LIST = "SET_UPLOAD_LIST";

export const APPEND_UPLOAD_LIST = "APPEND_UPLOAD_LIST";

export const UPDATE_UPLOAD_LIST_ITEM = "UPDATE_UPLOAD_LIST_ITEM";

export const SET_UPLOAD_INDICATOR = "SET_UPLOAD_INDICATOR";

export const USER_LOGOUT = "USER_LOGOUT";

export const SET_REFRESH_MODAL = "SET_REFRESH_MODAL";

export const APPEND_DOWNLOAD_LIST = 'APPEND_DOWNLOAD_LIST';

export const REMOVE_DOWNLOAD_LIST = 'REMOVE_DOWNLOAD_LIST';

export const UPDATE_DATASET_LIST = 'UPDATE_DATASET_LIST';

export const UPDATE_CLEAR_ID = 'UPDATE_CLEAR_ID';

export const SET_IS_LOGIN = 'SET_IS_LOGIN';
