export const ADD_DATASET_LIST = 'ADD_DATASET_LIST';

export const SET_DATASET_LIST = 'SET_DATASET_LIST';

export const CLEAN_DATASET_LIST = 'CLEAN_DATASET_LIST';

export const SET_USER_LIST = 'SET_USER_LIST';

export const SET_TAGS = 'SET_TAGS';

export const SET_METADATAS = 'SET_METADATAS';

export const SET_PERSONAL_DATASET_ID = 'SET_PERSONAL_DATASET_ID';

export const SET_CONTAINERS_PERMISSION = 'SET_CONTAINERS_PERMISSION';

export const SET_USER_ROLE = 'SET_USER_ROLE';

export const SET_UPLOAD_LIST = 'SET_UPLOAD_LIST';

export const APPEND_UPLOAD_LIST = 'APPEND_UPLOAD_LIST';

export const UPDATE_UPLOAD_LIST_ITEM = 'UPDATE_UPLOAD_LIST_ITEM';

export const SET_UPLOAD_INDICATOR = 'SET_UPLOAD_INDICATOR';

export const USER_LOGOUT = 'USER_LOGOUT';

export const SET_REFRESH_MODAL = 'SET_REFRESH_MODAL';

export const APPEND_DOWNLOAD_LIST = 'APPEND_DOWNLOAD_LIST';

export const REMOVE_DOWNLOAD_LIST = 'REMOVE_DOWNLOAD_LIST';

export const CLEAR_DOWNLOAD_LIST = 'CLEAR_DOWNLOAD_LIST';

export const UPDATE_COPY2CORE_LIST = 'UPDATE_COPY2CORE_LIST';
export const UPDATE_DATASET_LIST = 'UPDATE_DATASET_LIST';

export const UPDATE_CLEAR_ID = 'UPDATE_CLEAR_ID';

export const SET_IS_LOGIN = 'SET_IS_LOGIN';

export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_SUCCESS_NUM = 'SET_SUCCESS_NUM';
export const SET_DOWNLOAD_CLEAR_ID = 'SET_DOWNLOAD_CLEAR_ID';

export const SET_PANEL_ACTIVE_KEY = 'SET_PANEL_ACTIVE_KEY';

export const UPDATE_DOWNLOAD_ITEM = 'UPDATE_DOWNLOAD_ITEM';

export const SET_DOWNLOAD_LIST = 'SET_DOWNLOAD_LIST';

export const SET_CURRENT_PROJECT_PROFILE = 'SET_CURRENT_PROJECT_PROFILE';
export const SET_CURRENT_PROJECT_MANIFEST = 'SET_CURRENT_PROJECT_MANIFEST';
export const SET_CURRENT_PROJECT_TREE = 'SET_CURRENT_PROJECT_TREE';
export const SET_CURRENT_PROJECT_TREE_VFOLDER =
  'SET_CURRENT_PROJECT_TREE_VFOLDER';
export const SET_CURRENT_PROJECT_TREE_GREEN_ROOM =
  'SET_CURRENT_PROJECT_TREE_GREEN_ROOM';
export const SET_CURRENT_PROJECT_TREE_CORE = 'SET_CURRENT_PROJECT_TREE_CORE';
export const SET_CURRENT_PROJECT_ACTIVE_PANE =
  'SET_CURRENT_PROJECT_ACTIVE_PANE';
export const CLEAR_CURRENT_PROJECT = 'CLEAR_CURRENT_PROJECT';
export const TRIGGER_EVENT = 'TRIGGER_EVENT';
export const SET_EMAIL = 'SET_EMAIL';

export const SET_IS_KEYCLOAK_READY = 'SET_IS_KEYCLOAK_READY';
export const SET_IS_RELEASE_NOTE_SHOWN = 'SET_IS_RELEASE_NOTE_SHOWN';

export const SET_DELETE_LIST = 'SET_DELETE_LIST';
export const UPDATE_DELETE_LIST = 'UPDATE_DELETE_LIST';

export const SET_UPLOAD_FILE_MANIFEST = 'SET_UPLOAD_FILE_MANIFEST';

export const SET_SELECTED_FILES = 'SET_SELECTED_FILES';
export const SET_SELECTED_FILES_KEYS = 'SET_SELECTED_FILE_KEYS';
export const CLEAN_FILES_SELECTION = 'CLEAN_FILES_SELECTION';
export const SET_FOLDER_ROUTING = 'SET_FOLDER_ROUTING';
export const SHOW_SERVICE_REQUEST_RED_DOT = 'SHOW_SERVICE_REQUEST_RED_DOT';
