export const JOB_STATUS = {
  INIT: 'INIT',
  PRE_UPLOADED: 'PRE_UPLOADED',
  CHUNK_UPLOADED: 'CHUNK_UPLOADED',
  FINALIZED: 'FINALIZED',
  SUCCEED: 'SUCCEED',
  TERMINATED: 'TERMINATED',
  CANCELLED: 'CANCELLED',
  RUNNING: 'RUNNING',
  ZIPPING: 'ZIPPING',
  READY_FOR_DOWNLOADING: 'READY_FOR_DOWNLOADING',
};
