apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: utility
data:
  portal.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name _;
      location /vre {
          alias  /usr/share/nginx/html/vre/;
          index  index.html index.htm;
          try_files $uri $uri/ /vre/index.html;
          client_max_body_size 5m;

          # kill cache
          add_header Last-Modified $date_gmt;
          add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
          if_modified_since off;
          expires off;
          etag off;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
