export const modalityOptions = [
    'anatomical approach',
    'neuroimaging',
    'microscopy',
    'histological approach',
    'neural connectivity',
    'molecular expression characterization',
    'multimodal approach',
    'electrophysiology',
    'behavioral approach',
    'molecular expression approach',
    'cell population imaging',
    'physiological approach',
    'morphological approach',
    'cell morphology',
    'cell counting',
    'cell population characterization',
    'computational modeling',
  ];